### ISSUE TITLE
LifetimeTracker framework cannot be build on Xcode 9 / 9.1

### ISSUE THREAD

**Issue by huy-le** [krzysztofzablocki/LifetimeTracker#23]
I used Carthage to build this framework, but it failed. Then I tried to use Xcode to build the cloning from Carthage, it still failed.

I clone the v1.2 as well as master and try to build on Xcode 9/9.1. All failed by same errors. It is missing Constants type.

See attachments.

<img width="1512" alt="screen shot 2017-11-09 at 10 37 20 am" src="https://user-images.githubusercontent.com/3965573/32580629-474de8f8-c53a-11e7-8bb1-ff711294929d.png">

**Comment by krzysztofzablocki** [comment]
@tschob did we forget to include the file in pbxproj?

**Comment by tschob** [comment]
@krzysztofzablocki  Yes. I used the Example project to modify the library. Therefore the classes which I added aren't in the actual Xcode project. I have added them now and also added the actual Xcode project to the Example workspace. I also fixed the UIKit usage for non iOS targets.

The Carthage usage should work now again.

@huy-le The branch "issue/#23" should fix the build errors. You might have to clean your current checkout in the Carthage folder if it complains about "LifetimeTracker.xcodeproj cannot be opened because it is missing its project". The fix is part of pull request #24

**Comment by huy-le** [comment]
Thanks, will try it!

**Comment by tschob** [comment]
@huy-le You are welcome. Did it solve the issue for you?

**Comment by huy-le** [comment]
@tschob Yes, it did 👍 Thanks for prompt response.
