### ISSUE TITLE
Leak memory when change root view controller

### ISSUE THREAD

**Issue by phuongvnc** [krzysztofzablocki/LifetimeTracker#45]
When i changed root view controller for my app. Life time tracker show 4 leak memory in my app. I don't know it is issue when set `LifetimeConfiguration(maxCount: 1, groupName: "VC")` in BaseViewController

**Comment by berdikhan-fave** [comment]
I am facing exactly same issue, if I change RootViewController, I can see from my console and using Memory graph tool of Xcode that all my view controllers are been deallocated, while Lifetimetracker shows opposite.

**Comment by krzysztofzablocki** [comment]
@berdikhan-fave it tracks dealloc, you can try putting deinit func and breakpoint inside of it, see if its getting call and you should know if object is really deallocated

**Comment by berdikhan-fave** [comment]
I verified it using 3 ways:
1. I put `print("deinit")` at `deinit()` function of viewController
2. Xcode's Memory graph tool
3. https://twitter.com/0xced/status/900692839557992449 (Breakpoint) very useful by the way.

**Comment by krzysztofzablocki** [comment]
and LifetimeTracker still shows it as alive and even more so as leaking? whats the count it sees of the VC?

**Comment by berdikhan-fave** [comment]
Count is 1/1, supposed to be 0 or ideally not even in the list of Lifetimetracker

**Comment by berdikhan-fave** [comment]
[UPDATE] I was able to solve it by adding Lifetimtrackable to every viewController separately, as previously I added it to my BaseViewController and it didn't work all the time. Thanks @krzysztofzablocki for support.

**Comment by krzysztofzablocki** [comment]
@berdikhan-fave so I'm curious whether that means one of them was still alive?

**Comment by isimple4** [comment]
Sorry to comment on this closed issue, but I also run into this annoying issue.

Here is the thing. It actually is a bug due to the use of `static var` for `lifetimeConfiguration`. If you implement `LifetimeTrackable` in a base view controller which people would do for convenience use, all sub view controllers will shared the static `lifetimeConfiguration` instance since it is static. 

It would be alright if you have only one vc instance for one page, but when it comes to multiple instance, say a segment with couple of controllers to switch, the `configuration name` would be modified to the `last` name of `instance`. As a result, the count of instance usage will de deducted only to the `last` instance rather than others, so the tracker would report memory leak of these instance.

If we put the `lifetimeConfiguration` under every instance, it just works fine.

**Comment by krzysztofzablocki** [comment]
interesting, didn't think about it as I don't really use inheritance for things I usually track

**Comment by tschob** [comment]
@isimple4 do you have an example code of your setup? I used LifetimeTracker in base view controllers in multiple
projects. It worked fine with some convenience logic I added. I can prepare some example code later, but also would like to understand if this is actually the problem you faced

**Comment by isimple4** [comment]
@tschob Sure. Basically I just modified bit of source codes and copied them to my code base since I really don't want to implement `LifetimeTrackable` for every vc. But it's not a good practice though.

I need to change `static var` to instance `var` for protocol `LifetimeTrackable`, and also some related codes regarding `lifetimeConfiguration` in `LifetimeTracker.swift` file. Then every sub vc would contain  its own `lifetimeConfiguration` instance.

If you are not using multiple instances of different sub vc for one page, there should be no worries.

**Comment by isimple4** [comment]
For multiple instance scenario, codes would be something like below.

```swift
class BaseVC: LifetimeTrackable {
    static var lifetimeConfiguration = LifetimeConfiguration()
}

class SubVC1: BaseVC { }
class SubVC2: BaseVC { }

// This instance will report memory leak of SubVC1 and SubVC2.
// And SubVC3 instance would have a count of -2.
class SubVC3: BaseVC {
    let vc1 = SubVC1()
    let vc2 = SubVC2()
}
```

Hope it would clarify a bit.

**Comment by tschob** [comment]
@isimple4 I see. I modified the example project to reproduce the issue you face. Once I reentered a screen with multiple child VCs, I saw the weird behaviour! [see commit 1]

I think in general a deep dive into the library would be good to see if a proper fix can be made.

But you can also easily fix the issue in your project: Just make the configuration a computed property! [see commit 2]. What I also usually do in my projects is to create computed (class) properties which allows me to override e.g. the maxCount in children without implementing LifetimeTracker in all the VCs. [see commit 3].

Does this solve your issue / question?

**Comment by isimple4** [comment]
@tschob Your solution looks much better than mine. I'll give a try, thanks for that!
