### ISSUE TITLE
Failed to compile when installing version 1.4.0 from Cocoapods

### ISSUE THREAD

**Issue by yikuo123** [krzysztofzablocki/LifetimeTracker#47]
error messages as below :

> Argument of "#selector" fefers to instance method "toolbarPanned" that is not exposed to Objective-C
> Argument of "#selector" fefers to instance method "showPopover()" that is not exposed to Objective-C

**Comment by warren-gavin** [comment]
I had the same issue, but I noticed that this is already fixed in version `1.4.0`. 

Double check that you have the latest version number in your Podfile. If you don't then just update to `1.4.0` and you should be ok.

If you still have the same problem then this isn't a `LifetimeTracker` problem, it's likely you have an older version of Cocoapods installed (this is the problem I had)

Older versions of Cocoapods can't handle new versions of swift and this caused problems with your `pod install`. Instead of a warning Cocoapods will just give you the last version of `LifetimeTracker` that supports the latest version of swift understood by Cocoapods. 

@krzysztofzablocki Is there a minimum known version of Cocoapods?

**Comment by krzysztofzablocki** [comment]
@warren-gavin didn't really look into it, @yikuo123 can you check Podfile.lock to make sure it does have the latest version?
